### PR TITLE
feat(simple-authentication): add the management of CSRF token for the…

### PR DESCRIPTION
**Pull request by mathias-vandaele**
Add the management of CSRF token for the simple authentication

Another header has to be managed when operate has `CAMUNDA_OPERATE_CSRFPREVENTIONENABLED=true`
This PR allow `spring-zeebe` to manage the CSRF token if it has been enabled.

### CODE REVIEW

**Review by jonathanlukas — COMMENTED** [review]
Looks good so far. Did you try this as integration test?

**Comment by mathias-vandaele** [comment]
> Looks good so far. Did you try this as integration test?

I ran all UT, and started the camunda-core docker suite with `CAMUNDA_OPERATE_CSRFPREVENTIONENABLED=true` and `CAMUNDA_OPERATE_CSRFPREVENTIONENABLED=false` and verified with `ExampleApplication` that it was always pulling  tasks correctly from operate

**Comment by jonathanlukas** [comment]
Perfect :) then we can add this here.

Next steps: 
* backport to 8.5
* create issue for dedicated operate client repo

**Comment by johnBgood** [comment]
We'll also need to release `spring-zeebe` and bump its version in `connectors`, we can have a look together @mathias-vandaele if you're not sure how to do it

**Comment by jonathanlukas** [comment]
@johnBgood , after backporting you can simply create a release from the according branch with the next patch version tag which will trigger the action to release the artefacts

**Comment by johnBgood** [comment]
> @johnBgood , after backporting you can simply create a release from the according branch with the next patch version tag which will trigger the action to release the artefacts

Absolutely but I was not sure Mathias knew how to do it :)

**Pull request merged**
