### PR TITLE
Deploy DMN decision models via new deploy resource rpc

### PR DESCRIPTION
**Pull request by Lzgabel**
The Java client was already able to deploy DMN decision models, deploy DMN decision models via new deploy resource rpc.

### CODE REVIEW

**Comment by Lzgabel** [comment]
Hi @berndruecker. Please check this out in your free time. 🙇

**Comment by berndruecker** [comment]
Code looks good to me! 
But please note, that the existing code is also able to deploy DMN already (the deployProcess also takes DMN :-)).

My only concern I have is that this breaks backward compatibility to pre-8.0 versions (for a relatively small gain). @falko Do you have a spontaneous thought on this matter?

**Comment by falko** [comment]
I found it confusing that the old command does not list the DMN files. It made me think that it didn't work and I did something wrong.

Could we check with reflection if the new command is there and use it if it's there? The old one could be used as a fallback maybe combined with a warning that an old Zeebe client is used.

A warning that the Zeebe client version doesn't match the engine version could be a nice feature for Spring Zeebe anyway.

**Comment by falko** [comment]
@nevries feel free to chime in here.

**Comment by nevries** [comment]
I just hit the same issue, that is, DMN deployment works but the output does imply it wouldn't. I don't see a big issue with loosing compatibility with older client versions as the versioning of spring-zeebe was also updated to 8.x.x so having a client with this major release number makes sense to me. If there is a strong argument against it, I would support Falko's suggestion (reflection) given that the new command would fix the output problem.

**Comment by berndruecker** [comment]
Thanks for the input folks!

While I like the idea of reflection and the warning about versions, I don't see this as the biggest priority at the moment given the lack of time. 
I agree that breaking backward compatibility is not a big deal given we switched to 8.x - so I will merge this now.

**Pull request merged**
